name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests-ubuntu:
    name: Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pytest>=5.3 pycodestyle
          pip install cirq qiskit qsharp
      - name: Check style
        run: pycodestyle .
      - name: Run tests
        run: pytest .

  tests-windows:
    name: Tests (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pytest>=5.3 pycodestyle
          pip install cirq qiskit qsharp
      - name: Run tests
        run: pytest .
